// Copies the static public site + uploaded media into dist/ after the Vite admin build.
// Runs in Cloudflare Pages build (Node) and locally.
import { cp, mkdir, writeFile, access } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = resolve(root, 'dist');

async function exists(p) {
  try { await access(p); return true; } catch { return false; }
}

async function copyIfExists(rel, destRel = rel) {
  const src = resolve(root, rel);
  if (!(await exists(src))) { console.log(`skip (missing): ${rel}`); return; }
  const dest = resolve(dist, destRel);
  await mkdir(dirname(dest), { recursive: true });
  await cp(src, dest, { recursive: true });
  console.log(`copied: ${rel} -> dist/${destRel}`);
}

await mkdir(dist, { recursive: true });

// Public marketing site
await copyIfExists('index.html');
await copyIfExists('contract.html');
await copyIfExists('css');
await copyIfExists('js/app.js', 'js/app.js');
// Uploaded media (committed by /api/upload). Served at /uploads/...
await copyIfExists('uploads');
// SEO/hosting extras
await copyIfExists('CNAME');
await copyIfExists('favicon.ico');
await copyIfExists('robots.txt');

// Legacy admin URL → redirect to the new React admin at /admin/
await writeFile(
  resolve(dist, 'backoffice-yfm.html'),
  `<!DOCTYPE html><html lang="he" dir="rtl"><head><meta charset="UTF-8">` +
  `<meta http-equiv="refresh" content="0; url=/admin/"><title>מעבר לניהול…</title></head>` +
  `<body>מעבר למערכת הניהול… <a href="/admin/">לחצו כאן</a></body></html>\n`,
  'utf8'
);
console.log('wrote: dist/backoffice-yfm.html (redirect -> /admin/)');

// ---- Self-hosted vendor assets for the PUBLIC site (fonts + Font Awesome) ----
// Removes external CDN dependency (robust behind NetFree, no third-party requests).
const nm = resolve(root, 'node_modules');
const vendor = resolve(dist, 'vendor');

// Font Awesome: all.min.css + webfonts (all.min.css references ../webfonts relatively)
await cp(resolve(nm, '@fortawesome/fontawesome-free/webfonts'), resolve(vendor, 'fontawesome/webfonts'), { recursive: true });
await mkdir(resolve(vendor, 'fontawesome/css'), { recursive: true });
await cp(resolve(nm, '@fortawesome/fontawesome-free/css/all.min.css'), resolve(vendor, 'fontawesome/css/all.min.css'));
console.log('copied: Font Awesome -> dist/vendor/fontawesome/');

// Heebo + Frank Ruhl Libre woff2 (hebrew + latin subsets) → dist/vendor/fonts/ + generated CSS
const HEB = 'U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F';
const LAT = 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD';
const FONTS = [
  { pkg: 'heebo', family: 'Heebo', weights: [300, 400, 500, 600, 700, 800, 900] },
  { pkg: 'frank-ruhl-libre', family: 'Frank Ruhl Libre', weights: [500, 700, 900] },
];
await mkdir(resolve(vendor, 'fonts'), { recursive: true });
let fontCss = '/* Self-hosted fonts (generated by copy-static) */\n';
for (const f of FONTS) {
  for (const w of f.weights) {
    for (const [subset, range] of [['hebrew', HEB], ['latin', LAT]]) {
      const file = `${f.pkg}-${subset}-${w}-normal.woff2`;
      const srcFile = resolve(nm, `@fontsource/${f.pkg}/files/${file}`);
      if (!(await exists(srcFile))) continue;
      await cp(srcFile, resolve(vendor, 'fonts', file));
      fontCss += `@font-face{font-family:'${f.family}';font-style:normal;font-weight:${w};font-display:swap;` +
        `src:url('/vendor/fonts/${file}') format('woff2');unicode-range:${range};}\n`;
    }
  }
}
await writeFile(resolve(vendor, 'fonts.css'), fontCss, 'utf8');
console.log('copied: fonts -> dist/vendor/fonts/ + fonts.css');

console.log('copy-static done.');
